// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class CcdataMasterEntryT {
  private String part;
  private String file;
  private String name;

  public String getPart() { return part; }

  public void setPart(String part) { this.part = part; }

  public String getFile() { return file; }

  public void setFile(String file) { this.file = file; }

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }


  public CcdataMasterEntryT() {
    this.part = null;
    this.file = null;
    this.name = null;
  }
}

