// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class fbdc_additional_data extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static fbdc_additional_data getRootAsfbdc_additional_data(ByteBuffer _bb) { return getRootAsfbdc_additional_data(_bb, new fbdc_additional_data()); }
  public static fbdc_additional_data getRootAsfbdc_additional_data(ByteBuffer _bb, fbdc_additional_data obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public fbdc_additional_data __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String unk0() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk0AsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer unk0InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String unk1() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk1AsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer unk1InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createfbdc_additional_data(FlatBufferBuilder builder,
      int unk0Offset,
      int unk1Offset) {
    builder.startTable(2);
    fbdc_additional_data.addUnk1(builder, unk1Offset);
    fbdc_additional_data.addUnk0(builder, unk0Offset);
    return fbdc_additional_data.endfbdc_additional_data(builder);
  }

  public static void startfbdc_additional_data(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addUnk0(FlatBufferBuilder builder, int unk0Offset) { builder.addOffset(0, unk0Offset, 0); }
  public static void addUnk1(FlatBufferBuilder builder, int unk1Offset) { builder.addOffset(1, unk1Offset, 0); }
  public static int endfbdc_additional_data(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public fbdc_additional_data get(int j) { return get(new fbdc_additional_data(), j); }
    public fbdc_additional_data get(fbdc_additional_data obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public fbdc_additional_dataT unpack() {
    fbdc_additional_dataT _o = new fbdc_additional_dataT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(fbdc_additional_dataT _o) {
    String _oUnk0 = unk0();
    _o.setUnk0(_oUnk0);
    String _oUnk1 = unk1();
    _o.setUnk1(_oUnk1);
  }
  public static int pack(FlatBufferBuilder builder, fbdc_additional_dataT _o) {
    if (_o == null) return 0;
    int _unk0 = _o.getUnk0() == null ? 0 : builder.createString(_o.getUnk0());
    int _unk1 = _o.getUnk1() == null ? 0 : builder.createString(_o.getUnk1());
    return createfbdc_additional_data(
      builder,
      _unk0,
      _unk1);
  }
}

