// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ietc_data extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static ietc_data getRootAsietc_data(ByteBuffer _bb) { return getRootAsietc_data(_bb, new ietc_data()); }
  public static ietc_data getRootAsietc_data(ByteBuffer _bb, ietc_data obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ietc_data __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startietc_data(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endietc_data(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ietc_data get(int j) { return get(new ietc_data(), j); }
    public ietc_data get(ietc_data obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public ietc_dataT unpack() {
    ietc_dataT _o = new ietc_dataT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(ietc_dataT _o) {
  }
  public static int pack(FlatBufferBuilder builder, ietc_dataT _o) {
    if (_o == null) return 0;
    startietc_data(builder);
    return endietc_data(builder);
  }
}

