// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ModelLoadData extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static ModelLoadData getRootAsModelLoadData(ByteBuffer _bb) { return getRootAsModelLoadData(_bb, new ModelLoadData()); }
  public static ModelLoadData getRootAsModelLoadData(ByteBuffer _bb, ModelLoadData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ModelLoadData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String unk0() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk0AsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer unk0InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public float unk1() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk2(int j) { int o = __offset(8); return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0; }
  public int unk2Length() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public FloatVector unk2Vector() { return unk2Vector(new FloatVector()); }
  public FloatVector unk2Vector(FloatVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer unk2AsByteBuffer() { return __vector_as_bytebuffer(8, 4); }
  public ByteBuffer unk2InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 4); }

  public static int createModelLoadData(FlatBufferBuilder builder,
      int unk0Offset,
      float unk1,
      int unk2Offset) {
    builder.startTable(3);
    ModelLoadData.addUnk2(builder, unk2Offset);
    ModelLoadData.addUnk1(builder, unk1);
    ModelLoadData.addUnk0(builder, unk0Offset);
    return ModelLoadData.endModelLoadData(builder);
  }

  public static void startModelLoadData(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addUnk0(FlatBufferBuilder builder, int unk0Offset) { builder.addOffset(0, unk0Offset, 0); }
  public static void addUnk1(FlatBufferBuilder builder, float unk1) { builder.addFloat(1, unk1, 0.0f); }
  public static void addUnk2(FlatBufferBuilder builder, int unk2Offset) { builder.addOffset(2, unk2Offset, 0); }
  public static int createUnk2Vector(FlatBufferBuilder builder, float[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]); return builder.endVector(); }
  public static void startUnk2Vector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endModelLoadData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ModelLoadData get(int j) { return get(new ModelLoadData(), j); }
    public ModelLoadData get(ModelLoadData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public ModelLoadDataT unpack() {
    ModelLoadDataT _o = new ModelLoadDataT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(ModelLoadDataT _o) {
    String _oUnk0 = unk0();
    _o.setUnk0(_oUnk0);
    float _oUnk1 = unk1();
    _o.setUnk1(_oUnk1);
    float[] _oUnk2 = new float[unk2Length()];
    for (int _j = 0; _j < unk2Length(); ++_j) {_oUnk2[_j] = unk2(_j);}
    _o.setUnk2(_oUnk2);
  }
  public static int pack(FlatBufferBuilder builder, ModelLoadDataT _o) {
    if (_o == null) return 0;
    int _unk0 = _o.getUnk0() == null ? 0 : builder.createString(_o.getUnk0());
    int _unk2 = 0;
    if (_o.getUnk2() != null) {
      _unk2 = createUnk2Vector(builder, _o.getUnk2());
    }
    return createModelLoadData(
      builder,
      _unk0,
      _o.getUnk1(),
      _unk2);
  }
}

