// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class pe_AudioComponentT {
  private long unk0;
  private long unk1;
  private boolean unk2;
  private long unk3;
  private float unk4;

  public long getUnk0() { return unk0; }

  public void setUnk0(long unk0) { this.unk0 = unk0; }

  public long getUnk1() { return unk1; }

  public void setUnk1(long unk1) { this.unk1 = unk1; }

  public boolean getUnk2() { return unk2; }

  public void setUnk2(boolean unk2) { this.unk2 = unk2; }

  public long getUnk3() { return unk3; }

  public void setUnk3(long unk3) { this.unk3 = unk3; }

  public float getUnk4() { return unk4; }

  public void setUnk4(float unk4) { this.unk4 = unk4; }


  public pe_AudioComponentT() {
    this.unk0 = 0L;
    this.unk1 = 0L;
    this.unk2 = true;
    this.unk3 = 0L;
    this.unk4 = 0.0f;
  }
  public static pe_AudioComponentT deserializeFromBinary(byte[] fbBuffer) {
    return pe_AudioComponent.getRootAspe_AudioComponent(ByteBuffer.wrap(fbBuffer)).unpack();
  }
  public byte[] serializeToBinary() {
    FlatBufferBuilder fbb = new FlatBufferBuilder();
    pe_AudioComponent.finishpe_AudioComponentBuffer(fbb, pe_AudioComponent.pack(fbb, this));
    return fbb.sizedByteArray();
  }
}

