// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class pe_AudioListenerComponent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static pe_AudioListenerComponent getRootAspe_AudioListenerComponent(ByteBuffer _bb) { return getRootAspe_AudioListenerComponent(_bb, new pe_AudioListenerComponent()); }
  public static pe_AudioListenerComponent getRootAspe_AudioListenerComponent(ByteBuffer _bb, pe_AudioListenerComponent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public pe_AudioListenerComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String unk0() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk0AsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer unk0InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createpe_AudioListenerComponent(FlatBufferBuilder builder,
      int unk0Offset) {
    builder.startTable(1);
    pe_AudioListenerComponent.addUnk0(builder, unk0Offset);
    return pe_AudioListenerComponent.endpe_AudioListenerComponent(builder);
  }

  public static void startpe_AudioListenerComponent(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addUnk0(FlatBufferBuilder builder, int unk0Offset) { builder.addOffset(0, unk0Offset, 0); }
  public static int endpe_AudioListenerComponent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishpe_AudioListenerComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedpe_AudioListenerComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public pe_AudioListenerComponent get(int j) { return get(new pe_AudioListenerComponent(), j); }
    public pe_AudioListenerComponent get(pe_AudioListenerComponent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public pe_AudioListenerComponentT unpack() {
    pe_AudioListenerComponentT _o = new pe_AudioListenerComponentT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(pe_AudioListenerComponentT _o) {
    String _oUnk0 = unk0();
    _o.setUnk0(_oUnk0);
  }
  public static int pack(FlatBufferBuilder builder, pe_AudioListenerComponentT _o) {
    if (_o == null) return 0;
    int _unk0 = _o.getUnk0() == null ? 0 : builder.createString(_o.getUnk0());
    return createpe_AudioListenerComponent(
      builder,
      _unk0);
  }
}

