// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class pe_LightForWeatherT {
  private String unk0;
  private float unk1;
  private float unk2;
  private long unk3;
  private String unk4;
  private long unk5;
  private long unk6;
  private String unk7;
  private long unk8;
  private String unk9;

  public String getUnk0() { return unk0; }

  public void setUnk0(String unk0) { this.unk0 = unk0; }

  public float getUnk1() { return unk1; }

  public void setUnk1(float unk1) { this.unk1 = unk1; }

  public float getUnk2() { return unk2; }

  public void setUnk2(float unk2) { this.unk2 = unk2; }

  public long getUnk3() { return unk3; }

  public void setUnk3(long unk3) { this.unk3 = unk3; }

  public String getUnk4() { return unk4; }

  public void setUnk4(String unk4) { this.unk4 = unk4; }

  public long getUnk5() { return unk5; }

  public void setUnk5(long unk5) { this.unk5 = unk5; }

  public long getUnk6() { return unk6; }

  public void setUnk6(long unk6) { this.unk6 = unk6; }

  public String getUnk7() { return unk7; }

  public void setUnk7(String unk7) { this.unk7 = unk7; }

  public long getUnk8() { return unk8; }

  public void setUnk8(long unk8) { this.unk8 = unk8; }

  public String getUnk9() { return unk9; }

  public void setUnk9(String unk9) { this.unk9 = unk9; }


  public pe_LightForWeatherT() {
    this.unk0 = null;
    this.unk1 = 0.0f;
    this.unk2 = 0.0f;
    this.unk3 = 0L;
    this.unk4 = null;
    this.unk5 = 0L;
    this.unk6 = 0L;
    this.unk7 = null;
    this.unk8 = 0L;
    this.unk9 = null;
  }
  public static pe_LightForWeatherT deserializeFromBinary(byte[] fbBuffer) {
    return pe_LightForWeather.getRootAspe_LightForWeather(ByteBuffer.wrap(fbBuffer)).unpack();
  }
  public byte[] serializeToBinary() {
    FlatBufferBuilder fbb = new FlatBufferBuilder();
    pe_LightForWeather.finishpe_LightForWeatherBuffer(fbb, pe_LightForWeather.pack(fbb, this));
    return fbb.sizedByteArray();
  }
}

