// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class pe_UikitViewComponentT {
  private String filepath;
  private long unk1;
  private long unk2;
  private long unk3;
  private long unk4;
  private me.hydos.trifecta.flatbuffers.Titan.TrinityScene.uvc_data_1T[] unk5;
  private me.hydos.trifecta.flatbuffers.Titan.TrinityScene.uvc_data_2T[] unk6;

  public String getFilepath() { return filepath; }

  public void setFilepath(String filepath) { this.filepath = filepath; }

  public long getUnk1() { return unk1; }

  public void setUnk1(long unk1) { this.unk1 = unk1; }

  public long getUnk2() { return unk2; }

  public void setUnk2(long unk2) { this.unk2 = unk2; }

  public long getUnk3() { return unk3; }

  public void setUnk3(long unk3) { this.unk3 = unk3; }

  public long getUnk4() { return unk4; }

  public void setUnk4(long unk4) { this.unk4 = unk4; }

  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.uvc_data_1T[] getUnk5() { return unk5; }

  public void setUnk5(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.uvc_data_1T[] unk5) { this.unk5 = unk5; }

  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.uvc_data_2T[] getUnk6() { return unk6; }

  public void setUnk6(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.uvc_data_2T[] unk6) { this.unk6 = unk6; }


  public pe_UikitViewComponentT() {
    this.filepath = null;
    this.unk1 = 0L;
    this.unk2 = 0L;
    this.unk3 = 0L;
    this.unk4 = 0L;
    this.unk5 = null;
    this.unk6 = null;
  }
  public static pe_UikitViewComponentT deserializeFromBinary(byte[] fbBuffer) {
    return pe_UikitViewComponent.getRootAspe_UikitViewComponent(ByteBuffer.wrap(fbBuffer)).unpack();
  }
  public byte[] serializeToBinary() {
    FlatBufferBuilder fbb = new FlatBufferBuilder();
    pe_UikitViewComponent.finishpe_UikitViewComponentBuffer(fbb, pe_UikitViewComponent.pack(fbb, this));
    return fbb.sizedByteArray();
  }
}

