// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class PropertyT {
  private String name;
  private boolean value;
  private me.hydos.trifecta.flatbuffers.Titan.TrinityScene.someTable3T unk1;

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public boolean getValue() { return value; }

  public void setValue(boolean value) { this.value = value; }

  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.someTable3T getUnk1() { return unk1; }

  public void setUnk1(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.someTable3T unk1) { this.unk1 = unk1; }


  public PropertyT() {
    this.name = null;
    this.value = false;
    this.unk1 = null;
  }
}

