// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.Arrays;

public class SceneEntryT {
  private String typeName;
  private byte[] nestedType;
  private me.hydos.trifecta.flatbuffers.Titan.TrinityScene.SceneEntryT[] subObjects;

  public String getTypeName() { return typeName; }

  public void setTypeName(String typeName) { this.typeName = typeName; }

  public byte[] getNestedType() { return nestedType; }

  public void setNestedType(int[] nestedType) {
    // MODIFIED BY HYDOS
    this.nestedType = new byte[nestedType.length];
    for (var i = 0; i < nestedType.length; i++) this.nestedType[i] = (byte) nestedType[i];
  }

  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.SceneEntryT[] getSubObjects() { return subObjects; }

  public void setSubObjects(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.SceneEntryT[] subObjects) { this.subObjects = subObjects; }


  public SceneEntryT() {
    this.typeName = null;
    this.nestedType = null;
    this.subObjects = null;
  }
}

