// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class someTable3 extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static someTable3 getRootAssomeTable3(ByteBuffer _bb) { return getRootAssomeTable3(_bb, new someTable3()); }
  public static someTable3 getRootAssomeTable3(ByteBuffer _bb, someTable3 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public someTable3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long unk0() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean unk1() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createsomeTable3(FlatBufferBuilder builder,
      long unk0,
      boolean unk1) {
    builder.startTable(2);
    someTable3.addUnk0(builder, unk0);
    someTable3.addUnk1(builder, unk1);
    return someTable3.endsomeTable3(builder);
  }

  public static void startsomeTable3(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addUnk0(FlatBufferBuilder builder, long unk0) { builder.addLong(0, unk0, 0L); }
  public static void addUnk1(FlatBufferBuilder builder, boolean unk1) { builder.addBoolean(1, unk1, false); }
  public static int endsomeTable3(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public someTable3 get(int j) { return get(new someTable3(), j); }
    public someTable3 get(someTable3 obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public someTable3T unpack() {
    someTable3T _o = new someTable3T();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(someTable3T _o) {
    long _oUnk0 = unk0();
    _o.setUnk0(_oUnk0);
    boolean _oUnk1 = unk1();
    _o.setUnk1(_oUnk1);
  }
  public static int pack(FlatBufferBuilder builder, someTable3T _o) {
    if (_o == null) return 0;
    return createsomeTable3(
      builder,
      _o.getUnk0(),
      _o.getUnk1());
  }
}

