// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class someTable2 extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static someTable2 getRootAssomeTable2(ByteBuffer _bb) { return getRootAssomeTable2(_bb, new someTable2()); }
  public static someTable2 getRootAssomeTable2(ByteBuffer _bb, someTable2 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public someTable2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startsomeTable2(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endsomeTable2(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public someTable2 get(int j) { return get(new someTable2(), j); }
    public someTable2 get(someTable2 obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public someTable2T unpack() {
    someTable2T _o = new someTable2T();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(someTable2T _o) {
  }
  public static int pack(FlatBufferBuilder builder, someTable2T _o) {
    if (_o == null) return 0;
    startsomeTable2(builder);
    return endsomeTable2(builder);
  }
}

