// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class SP_PointT {
  private String name;
  private me.hydos.trifecta.flatbuffers.Vec3fT position;

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public me.hydos.trifecta.flatbuffers.Vec3fT getPosition() { return position; }

  public void setPosition(me.hydos.trifecta.flatbuffers.Vec3fT position) { this.position = position; }


  public SP_PointT() {
    this.name = null;
    this.position = new me.hydos.trifecta.flatbuffers.Vec3fT();
  }
}

