// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ti_PokeVoiceComponent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static ti_PokeVoiceComponent getRootAsti_PokeVoiceComponent(ByteBuffer _bb) { return getRootAsti_PokeVoiceComponent(_bb, new ti_PokeVoiceComponent()); }
  public static ti_PokeVoiceComponent getRootAsti_PokeVoiceComponent(ByteBuffer _bb, ti_PokeVoiceComponent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ti_PokeVoiceComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int name() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }

  public static int createti_PokeVoiceComponent(FlatBufferBuilder builder,
      int name) {
    builder.startTable(1);
    ti_PokeVoiceComponent.addName(builder, name);
    return ti_PokeVoiceComponent.endti_PokeVoiceComponent(builder);
  }

  public static void startti_PokeVoiceComponent(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addName(FlatBufferBuilder builder, int name) { builder.addShort(0, (short) name, (short) 0); }
  public static int endti_PokeVoiceComponent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishti_PokeVoiceComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedti_PokeVoiceComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ti_PokeVoiceComponent get(int j) { return get(new ti_PokeVoiceComponent(), j); }
    public ti_PokeVoiceComponent get(ti_PokeVoiceComponent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public ti_PokeVoiceComponentT unpack() {
    ti_PokeVoiceComponentT _o = new ti_PokeVoiceComponentT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(ti_PokeVoiceComponentT _o) {
    int _oName = name();
    _o.setName(_oName);
  }
  public static int pack(FlatBufferBuilder builder, ti_PokeVoiceComponentT _o) {
    if (_o == null) return 0;
    return createti_PokeVoiceComponent(
      builder,
      _o.getName());
  }
}

