// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class trinity_LayoutComponent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static trinity_LayoutComponent getRootAstrinity_LayoutComponent(ByteBuffer _bb) { return getRootAstrinity_LayoutComponent(_bb, new trinity_LayoutComponent()); }
  public static trinity_LayoutComponent getRootAstrinity_LayoutComponent(ByteBuffer _bb, trinity_LayoutComponent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public trinity_LayoutComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String filePath() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer filePathAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer filePathInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String layoutFileName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer layoutFileNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer layoutFileNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public long unk2() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public boolean unk3() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String componentName() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer componentNameAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer componentNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }

  public static int createtrinity_LayoutComponent(FlatBufferBuilder builder,
      int filePathOffset,
      int layoutFileNameOffset,
      long unk2,
      boolean unk3,
      int componentNameOffset) {
    builder.startTable(5);
    trinity_LayoutComponent.addComponentName(builder, componentNameOffset);
    trinity_LayoutComponent.addUnk2(builder, unk2);
    trinity_LayoutComponent.addLayoutFileName(builder, layoutFileNameOffset);
    trinity_LayoutComponent.addFilePath(builder, filePathOffset);
    trinity_LayoutComponent.addUnk3(builder, unk3);
    return trinity_LayoutComponent.endtrinity_LayoutComponent(builder);
  }

  public static void starttrinity_LayoutComponent(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addFilePath(FlatBufferBuilder builder, int filePathOffset) { builder.addOffset(0, filePathOffset, 0); }
  public static void addLayoutFileName(FlatBufferBuilder builder, int layoutFileNameOffset) { builder.addOffset(1, layoutFileNameOffset, 0); }
  public static void addUnk2(FlatBufferBuilder builder, long unk2) { builder.addInt(2, (int) unk2, (int) 0L); }
  public static void addUnk3(FlatBufferBuilder builder, boolean unk3) { builder.addBoolean(3, unk3, false); }
  public static void addComponentName(FlatBufferBuilder builder, int componentNameOffset) { builder.addOffset(4, componentNameOffset, 0); }
  public static int endtrinity_LayoutComponent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishtrinity_LayoutComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedtrinity_LayoutComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public trinity_LayoutComponent get(int j) { return get(new trinity_LayoutComponent(), j); }
    public trinity_LayoutComponent get(trinity_LayoutComponent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public trinity_LayoutComponentT unpack() {
    trinity_LayoutComponentT _o = new trinity_LayoutComponentT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(trinity_LayoutComponentT _o) {
    String _oFilePath = filePath();
    _o.setFilePath(_oFilePath);
    String _oLayoutFileName = layoutFileName();
    _o.setLayoutFileName(_oLayoutFileName);
    long _oUnk2 = unk2();
    _o.setUnk2(_oUnk2);
    boolean _oUnk3 = unk3();
    _o.setUnk3(_oUnk3);
    String _oComponentName = componentName();
    _o.setComponentName(_oComponentName);
  }
  public static int pack(FlatBufferBuilder builder, trinity_LayoutComponentT _o) {
    if (_o == null) return 0;
    int _filePath = _o.getFilePath() == null ? 0 : builder.createString(_o.getFilePath());
    int _layoutFileName = _o.getLayoutFileName() == null ? 0 : builder.createString(_o.getLayoutFileName());
    int _componentName = _o.getComponentName() == null ? 0 : builder.createString(_o.getComponentName());
    return createtrinity_LayoutComponent(
      builder,
      _filePath,
      _layoutFileName,
      _o.getUnk2(),
      _o.getUnk3(),
      _componentName);
  }
}

