// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class trinity_Locator extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static trinity_Locator getRootAstrinity_Locator(ByteBuffer _bb) { return getRootAstrinity_Locator(_bb, new trinity_Locator()); }
  public static trinity_Locator getRootAstrinity_Locator(ByteBuffer _bb, trinity_Locator obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public trinity_Locator __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String filePath() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer filePathAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer filePathInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createtrinity_Locator(FlatBufferBuilder builder,
      int filePathOffset,
      int nameOffset) {
    builder.startTable(2);
    trinity_Locator.addName(builder, nameOffset);
    trinity_Locator.addFilePath(builder, filePathOffset);
    return trinity_Locator.endtrinity_Locator(builder);
  }

  public static void starttrinity_Locator(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addFilePath(FlatBufferBuilder builder, int filePathOffset) { builder.addOffset(0, filePathOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static int endtrinity_Locator(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishtrinity_LocatorBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedtrinity_LocatorBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public trinity_Locator get(int j) { return get(new trinity_Locator(), j); }
    public trinity_Locator get(trinity_Locator obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public trinity_LocatorT unpack() {
    trinity_LocatorT _o = new trinity_LocatorT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(trinity_LocatorT _o) {
    String _oFilePath = filePath();
    _o.setFilePath(_oFilePath);
    String _oName = name();
    _o.setName(_oName);
  }
  public static int pack(FlatBufferBuilder builder, trinity_LocatorT _o) {
    if (_o == null) return 0;
    int _filePath = _o.getFilePath() == null ? 0 : builder.createString(_o.getFilePath());
    int _name = _o.getName() == null ? 0 : builder.createString(_o.getName());
    return createtrinity_Locator(
      builder,
      _filePath,
      _name);
  }
}

