// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class trinity_ModelComponent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static trinity_ModelComponent getRootAstrinity_ModelComponent(ByteBuffer _bb) { return getRootAstrinity_ModelComponent(_bb, new trinity_ModelComponent()); }
  public static trinity_ModelComponent getRootAstrinity_ModelComponent(ByteBuffer _bb, trinity_ModelComponent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public trinity_ModelComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String modelFilePath() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer modelFilePathAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer modelFilePathInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String materialOverrideFilePath() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer materialOverrideFilePathAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer materialOverrideFilePathInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String unk3() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk3AsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer unk3InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public boolean unk4() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public float unk5() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk6() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk7() { int o = __offset(18); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public long unk8() { int o = __offset(20); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public float unk9() { int o = __offset(22); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public long unk10() { int o = __offset(24); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public float unk11() { int o = __offset(26); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public String unk12() { int o = __offset(28); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk12AsByteBuffer() { return __vector_as_bytebuffer(28, 1); }
  public ByteBuffer unk12InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 28, 1); }
  public float unk13() { int o = __offset(30); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public String unk14() { int o = __offset(32); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk14AsByteBuffer() { return __vector_as_bytebuffer(32, 1); }
  public ByteBuffer unk14InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 32, 1); }
  public float unk15() { int o = __offset(34); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public long unk16() { int o = __offset(36); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public boolean unk17() { int o = __offset(38); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }
  public long unk18() { int o = __offset(40); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String unk19() { int o = __offset(42); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk19AsByteBuffer() { return __vector_as_bytebuffer(42, 1); }
  public ByteBuffer unk19InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 42, 1); }
  public String unk20() { int o = __offset(44); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk20AsByteBuffer() { return __vector_as_bytebuffer(44, 1); }
  public ByteBuffer unk20InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 44, 1); }
  public boolean unk21() { int o = __offset(46); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String unk22() { int o = __offset(48); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk22AsByteBuffer() { return __vector_as_bytebuffer(48, 1); }
  public ByteBuffer unk22InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 48, 1); }
  public boolean unk23() { int o = __offset(50); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createtrinity_ModelComponent(FlatBufferBuilder builder,
      int modelFilePathOffset,
      int nameOffset,
      int materialOverrideFilePathOffset,
      int unk3Offset,
      boolean unk4,
      float unk5,
      float unk6,
      float unk7,
      long unk8,
      float unk9,
      long unk10,
      float unk11,
      int unk12Offset,
      float unk13,
      int unk14Offset,
      float unk15,
      long unk16,
      boolean unk17,
      long unk18,
      int unk19Offset,
      int unk20Offset,
      boolean unk21,
      int unk22Offset,
      boolean unk23) {
    builder.startTable(24);
    trinity_ModelComponent.addUnk22(builder, unk22Offset);
    trinity_ModelComponent.addUnk20(builder, unk20Offset);
    trinity_ModelComponent.addUnk19(builder, unk19Offset);
    trinity_ModelComponent.addUnk18(builder, unk18);
    trinity_ModelComponent.addUnk16(builder, unk16);
    trinity_ModelComponent.addUnk15(builder, unk15);
    trinity_ModelComponent.addUnk14(builder, unk14Offset);
    trinity_ModelComponent.addUnk13(builder, unk13);
    trinity_ModelComponent.addUnk12(builder, unk12Offset);
    trinity_ModelComponent.addUnk11(builder, unk11);
    trinity_ModelComponent.addUnk10(builder, unk10);
    trinity_ModelComponent.addUnk9(builder, unk9);
    trinity_ModelComponent.addUnk8(builder, unk8);
    trinity_ModelComponent.addUnk7(builder, unk7);
    trinity_ModelComponent.addUnk6(builder, unk6);
    trinity_ModelComponent.addUnk5(builder, unk5);
    trinity_ModelComponent.addUnk3(builder, unk3Offset);
    trinity_ModelComponent.addMaterialOverrideFilePath(builder, materialOverrideFilePathOffset);
    trinity_ModelComponent.addName(builder, nameOffset);
    trinity_ModelComponent.addModelFilePath(builder, modelFilePathOffset);
    trinity_ModelComponent.addUnk23(builder, unk23);
    trinity_ModelComponent.addUnk21(builder, unk21);
    trinity_ModelComponent.addUnk17(builder, unk17);
    trinity_ModelComponent.addUnk4(builder, unk4);
    return trinity_ModelComponent.endtrinity_ModelComponent(builder);
  }

  public static void starttrinity_ModelComponent(FlatBufferBuilder builder) { builder.startTable(24); }
  public static void addModelFilePath(FlatBufferBuilder builder, int modelFilePathOffset) { builder.addOffset(0, modelFilePathOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addMaterialOverrideFilePath(FlatBufferBuilder builder, int materialOverrideFilePathOffset) { builder.addOffset(2, materialOverrideFilePathOffset, 0); }
  public static void addUnk3(FlatBufferBuilder builder, int unk3Offset) { builder.addOffset(3, unk3Offset, 0); }
  public static void addUnk4(FlatBufferBuilder builder, boolean unk4) { builder.addBoolean(4, unk4, false); }
  public static void addUnk5(FlatBufferBuilder builder, float unk5) { builder.addFloat(5, unk5, 0.0f); }
  public static void addUnk6(FlatBufferBuilder builder, float unk6) { builder.addFloat(6, unk6, 0.0f); }
  public static void addUnk7(FlatBufferBuilder builder, float unk7) { builder.addFloat(7, unk7, 0.0f); }
  public static void addUnk8(FlatBufferBuilder builder, long unk8) { builder.addInt(8, (int) unk8, (int) 0L); }
  public static void addUnk9(FlatBufferBuilder builder, float unk9) { builder.addFloat(9, unk9, 0.0f); }
  public static void addUnk10(FlatBufferBuilder builder, long unk10) { builder.addInt(10, (int) unk10, (int) 0L); }
  public static void addUnk11(FlatBufferBuilder builder, float unk11) { builder.addFloat(11, unk11, 0.0f); }
  public static void addUnk12(FlatBufferBuilder builder, int unk12Offset) { builder.addOffset(12, unk12Offset, 0); }
  public static void addUnk13(FlatBufferBuilder builder, float unk13) { builder.addFloat(13, unk13, 0.0f); }
  public static void addUnk14(FlatBufferBuilder builder, int unk14Offset) { builder.addOffset(14, unk14Offset, 0); }
  public static void addUnk15(FlatBufferBuilder builder, float unk15) { builder.addFloat(15, unk15, 0.0f); }
  public static void addUnk16(FlatBufferBuilder builder, long unk16) { builder.addInt(16, (int) unk16, (int) 0L); }
  public static void addUnk17(FlatBufferBuilder builder, boolean unk17) { builder.addBoolean(17, unk17, true); }
  public static void addUnk18(FlatBufferBuilder builder, long unk18) { builder.addInt(18, (int) unk18, (int) 0L); }
  public static void addUnk19(FlatBufferBuilder builder, int unk19Offset) { builder.addOffset(19, unk19Offset, 0); }
  public static void addUnk20(FlatBufferBuilder builder, int unk20Offset) { builder.addOffset(20, unk20Offset, 0); }
  public static void addUnk21(FlatBufferBuilder builder, boolean unk21) { builder.addBoolean(21, unk21, false); }
  public static void addUnk22(FlatBufferBuilder builder, int unk22Offset) { builder.addOffset(22, unk22Offset, 0); }
  public static void addUnk23(FlatBufferBuilder builder, boolean unk23) { builder.addBoolean(23, unk23, false); }
  public static int endtrinity_ModelComponent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishtrinity_ModelComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedtrinity_ModelComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public trinity_ModelComponent get(int j) { return get(new trinity_ModelComponent(), j); }
    public trinity_ModelComponent get(trinity_ModelComponent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public trinity_ModelComponentT unpack() {
    trinity_ModelComponentT _o = new trinity_ModelComponentT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(trinity_ModelComponentT _o) {
    String _oModelFilePath = modelFilePath();
    _o.setModelFilePath(_oModelFilePath);
    String _oName = name();
    _o.setName(_oName);
    String _oMaterialOverrideFilePath = materialOverrideFilePath();
    _o.setMaterialOverrideFilePath(_oMaterialOverrideFilePath);
    String _oUnk3 = unk3();
    _o.setUnk3(_oUnk3);
    boolean _oUnk4 = unk4();
    _o.setUnk4(_oUnk4);
    float _oUnk5 = unk5();
    _o.setUnk5(_oUnk5);
    float _oUnk6 = unk6();
    _o.setUnk6(_oUnk6);
    float _oUnk7 = unk7();
    _o.setUnk7(_oUnk7);
    long _oUnk8 = unk8();
    _o.setUnk8(_oUnk8);
    float _oUnk9 = unk9();
    _o.setUnk9(_oUnk9);
    long _oUnk10 = unk10();
    _o.setUnk10(_oUnk10);
    float _oUnk11 = unk11();
    _o.setUnk11(_oUnk11);
    String _oUnk12 = unk12();
    _o.setUnk12(_oUnk12);
    float _oUnk13 = unk13();
    _o.setUnk13(_oUnk13);
    String _oUnk14 = unk14();
    _o.setUnk14(_oUnk14);
    float _oUnk15 = unk15();
    _o.setUnk15(_oUnk15);
    long _oUnk16 = unk16();
    _o.setUnk16(_oUnk16);
    boolean _oUnk17 = unk17();
    _o.setUnk17(_oUnk17);
    long _oUnk18 = unk18();
    _o.setUnk18(_oUnk18);
    String _oUnk19 = unk19();
    _o.setUnk19(_oUnk19);
    String _oUnk20 = unk20();
    _o.setUnk20(_oUnk20);
    boolean _oUnk21 = unk21();
    _o.setUnk21(_oUnk21);
    String _oUnk22 = unk22();
    _o.setUnk22(_oUnk22);
    boolean _oUnk23 = unk23();
    _o.setUnk23(_oUnk23);
  }
  public static int pack(FlatBufferBuilder builder, trinity_ModelComponentT _o) {
    if (_o == null) return 0;
    int _modelFilePath = _o.getModelFilePath() == null ? 0 : builder.createString(_o.getModelFilePath());
    int _name = _o.getName() == null ? 0 : builder.createString(_o.getName());
    int _materialOverrideFilePath = _o.getMaterialOverrideFilePath() == null ? 0 : builder.createString(_o.getMaterialOverrideFilePath());
    int _unk3 = _o.getUnk3() == null ? 0 : builder.createString(_o.getUnk3());
    int _unk12 = _o.getUnk12() == null ? 0 : builder.createString(_o.getUnk12());
    int _unk14 = _o.getUnk14() == null ? 0 : builder.createString(_o.getUnk14());
    int _unk19 = _o.getUnk19() == null ? 0 : builder.createString(_o.getUnk19());
    int _unk20 = _o.getUnk20() == null ? 0 : builder.createString(_o.getUnk20());
    int _unk22 = _o.getUnk22() == null ? 0 : builder.createString(_o.getUnk22());
    return createtrinity_ModelComponent(
      builder,
      _modelFilePath,
      _name,
      _materialOverrideFilePath,
      _unk3,
      _o.getUnk4(),
      _o.getUnk5(),
      _o.getUnk6(),
      _o.getUnk7(),
      _o.getUnk8(),
      _o.getUnk9(),
      _o.getUnk10(),
      _o.getUnk11(),
      _unk12,
      _o.getUnk13(),
      _unk14,
      _o.getUnk15(),
      _o.getUnk16(),
      _o.getUnk17(),
      _o.getUnk18(),
      _unk19,
      _unk20,
      _o.getUnk21(),
      _unk22,
      _o.getUnk23());
  }
}

