// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class trinity_AnimationComponentT {
  private String filePath;
  private long name;
  private boolean unk2;
  private float unk3;
  private long unk4;
  private float unk5;
  private long unk6;
  private float unk7;
  private long res8;
  private float unk9;
  private long unk10;
  private long res11;

  public String getFilePath() { return filePath; }

  public void setFilePath(String filePath) { this.filePath = filePath; }

  public long getName() { return name; }

  public void setName(long name) { this.name = name; }

  public boolean getUnk2() { return unk2; }

  public void setUnk2(boolean unk2) { this.unk2 = unk2; }

  public float getUnk3() { return unk3; }

  public void setUnk3(float unk3) { this.unk3 = unk3; }

  public long getUnk4() { return unk4; }

  public void setUnk4(long unk4) { this.unk4 = unk4; }

  public float getUnk5() { return unk5; }

  public void setUnk5(float unk5) { this.unk5 = unk5; }

  public long getUnk6() { return unk6; }

  public void setUnk6(long unk6) { this.unk6 = unk6; }

  public float getUnk7() { return unk7; }

  public void setUnk7(float unk7) { this.unk7 = unk7; }

  public long getRes8() { return res8; }

  public void setRes8(long res8) { this.res8 = res8; }

  public float getUnk9() { return unk9; }

  public void setUnk9(float unk9) { this.unk9 = unk9; }

  public long getUnk10() { return unk10; }

  public void setUnk10(long unk10) { this.unk10 = unk10; }

  public long getRes11() { return res11; }

  public void setRes11(long res11) { this.res11 = res11; }


  public trinity_AnimationComponentT() {
    this.filePath = null;
    this.name = 0L;
    this.unk2 = false;
    this.unk3 = 0.0f;
    this.unk4 = 0L;
    this.unk5 = 0.0f;
    this.unk6 = 0L;
    this.unk7 = 0.0f;
    this.res8 = 0L;
    this.unk9 = 0.0f;
    this.unk10 = 0L;
    this.res11 = 0L;
  }
  public static trinity_AnimationComponentT deserializeFromBinary(byte[] fbBuffer) {
    return trinity_AnimationComponent.getRootAstrinity_AnimationComponent(ByteBuffer.wrap(fbBuffer)).unpack();
  }
  public byte[] serializeToBinary() {
    FlatBufferBuilder fbb = new FlatBufferBuilder();
    trinity_AnimationComponent.finishtrinity_AnimationComponentBuffer(fbb, trinity_AnimationComponent.pack(fbb, this));
    return fbb.sizedByteArray();
  }
}

