// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class trinity_CharacterCreationMasterComponentT {
  private String name;
  private boolean res1;
  private float unk2;
  private float unk3;
  private float unk4;
  private boolean res5;
  private float unk6;
  private long unk7;
  private float unk8;
  private long unk9;
  private float unk10;
  private long unk11;
  private float unk12;
  private long res13;
  private long res14;
  private me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntryT[] ccdataMasterList;
  private me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcDataT[] unk16;
  private boolean res17;

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public boolean getRes1() { return res1; }

  public void setRes1(boolean res1) { this.res1 = res1; }

  public float getUnk2() { return unk2; }

  public void setUnk2(float unk2) { this.unk2 = unk2; }

  public float getUnk3() { return unk3; }

  public void setUnk3(float unk3) { this.unk3 = unk3; }

  public float getUnk4() { return unk4; }

  public void setUnk4(float unk4) { this.unk4 = unk4; }

  public boolean getRes5() { return res5; }

  public void setRes5(boolean res5) { this.res5 = res5; }

  public float getUnk6() { return unk6; }

  public void setUnk6(float unk6) { this.unk6 = unk6; }

  public long getUnk7() { return unk7; }

  public void setUnk7(long unk7) { this.unk7 = unk7; }

  public float getUnk8() { return unk8; }

  public void setUnk8(float unk8) { this.unk8 = unk8; }

  public long getUnk9() { return unk9; }

  public void setUnk9(long unk9) { this.unk9 = unk9; }

  public float getUnk10() { return unk10; }

  public void setUnk10(float unk10) { this.unk10 = unk10; }

  public long getUnk11() { return unk11; }

  public void setUnk11(long unk11) { this.unk11 = unk11; }

  public float getUnk12() { return unk12; }

  public void setUnk12(float unk12) { this.unk12 = unk12; }

  public long getRes13() { return res13; }

  public void setRes13(long res13) { this.res13 = res13; }

  public long getRes14() { return res14; }

  public void setRes14(long res14) { this.res14 = res14; }

  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntryT[] getCcdataMasterList() { return ccdataMasterList; }

  public void setCcdataMasterList(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntryT[] ccdataMasterList) { this.ccdataMasterList = ccdataMasterList; }

  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcDataT[] getUnk16() { return unk16; }

  public void setUnk16(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcDataT[] unk16) { this.unk16 = unk16; }

  public boolean getRes17() { return res17; }

  public void setRes17(boolean res17) { this.res17 = res17; }


  public trinity_CharacterCreationMasterComponentT() {
    this.name = null;
    this.res1 = false;
    this.unk2 = 0.0f;
    this.unk3 = 0.0f;
    this.unk4 = 0.0f;
    this.res5 = false;
    this.unk6 = 0.0f;
    this.unk7 = 0L;
    this.unk8 = 0.0f;
    this.unk9 = 0L;
    this.unk10 = 0.0f;
    this.unk11 = 0L;
    this.unk12 = 0.0f;
    this.res13 = 0L;
    this.res14 = 0L;
    this.ccdataMasterList = null;
    this.unk16 = null;
    this.res17 = false;
  }
  public static trinity_CharacterCreationMasterComponentT deserializeFromBinary(byte[] fbBuffer) {
    return trinity_CharacterCreationMasterComponent.getRootAstrinity_CharacterCreationMasterComponent(ByteBuffer.wrap(fbBuffer)).unpack();
  }
  public byte[] serializeToBinary() {
    FlatBufferBuilder fbb = new FlatBufferBuilder();
    trinity_CharacterCreationMasterComponent.finishtrinity_CharacterCreationMasterComponentBuffer(fbb, trinity_CharacterCreationMasterComponent.pack(fbb, this));
    return fbb.sizedByteArray();
  }
}

