// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class trinity_ParticleComponentT {
  private String filePath;
  private String unk1;
  private boolean unk2;
  private String particleName;
  private String particleParent;
  private long unk5;
  private boolean unk6;
  private boolean unk7;
  private long unk8;
  private long unk9;
  private float unk10;
  private boolean unk11;

  public String getFilePath() { return filePath; }

  public void setFilePath(String filePath) { this.filePath = filePath; }

  public String getUnk1() { return unk1; }

  public void setUnk1(String unk1) { this.unk1 = unk1; }

  public boolean getUnk2() { return unk2; }

  public void setUnk2(boolean unk2) { this.unk2 = unk2; }

  public String getParticleName() { return particleName; }

  public void setParticleName(String particleName) { this.particleName = particleName; }

  public String getParticleParent() { return particleParent; }

  public void setParticleParent(String particleParent) { this.particleParent = particleParent; }

  public long getUnk5() { return unk5; }

  public void setUnk5(long unk5) { this.unk5 = unk5; }

  public boolean getUnk6() { return unk6; }

  public void setUnk6(boolean unk6) { this.unk6 = unk6; }

  public boolean getUnk7() { return unk7; }

  public void setUnk7(boolean unk7) { this.unk7 = unk7; }

  public long getUnk8() { return unk8; }

  public void setUnk8(long unk8) { this.unk8 = unk8; }

  public long getUnk9() { return unk9; }

  public void setUnk9(long unk9) { this.unk9 = unk9; }

  public float getUnk10() { return unk10; }

  public void setUnk10(float unk10) { this.unk10 = unk10; }

  public boolean getUnk11() { return unk11; }

  public void setUnk11(boolean unk11) { this.unk11 = unk11; }


  public trinity_ParticleComponentT() {
    this.filePath = null;
    this.unk1 = null;
    this.unk2 = false;
    this.particleName = null;
    this.particleParent = null;
    this.unk5 = 0L;
    this.unk6 = false;
    this.unk7 = false;
    this.unk8 = 0L;
    this.unk9 = 0L;
    this.unk10 = 0.0f;
    this.unk11 = true;
  }
  public static trinity_ParticleComponentT deserializeFromBinary(byte[] fbBuffer) {
    return trinity_ParticleComponent.getRootAstrinity_ParticleComponent(ByteBuffer.wrap(fbBuffer)).unpack();
  }
  public byte[] serializeToBinary() {
    FlatBufferBuilder fbb = new FlatBufferBuilder();
    trinity_ParticleComponent.finishtrinity_ParticleComponentBuffer(fbb, trinity_ParticleComponent.pack(fbb, this));
    return fbb.sizedByteArray();
  }
}

