// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class trinity_CharacterCreationMasterComponent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static trinity_CharacterCreationMasterComponent getRootAstrinity_CharacterCreationMasterComponent(ByteBuffer _bb) { return getRootAstrinity_CharacterCreationMasterComponent(_bb, new trinity_CharacterCreationMasterComponent()); }
  public static trinity_CharacterCreationMasterComponent getRootAstrinity_CharacterCreationMasterComponent(ByteBuffer _bb, trinity_CharacterCreationMasterComponent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public trinity_CharacterCreationMasterComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public boolean res1() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public float unk2() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk3() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk4() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public boolean res5() { int o = __offset(14); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public float unk6() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public long unk7() { int o = __offset(18); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public float unk8() { int o = __offset(20); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public long unk9() { int o = __offset(22); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public float unk10() { int o = __offset(24); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public long unk11() { int o = __offset(26); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public float unk12() { int o = __offset(28); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public long res13() { int o = __offset(30); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long res14() { int o = __offset(32); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntry ccdataMasterList(int j) { return ccdataMasterList(new me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntry(), j); }
  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntry ccdataMasterList(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntry obj, int j) { int o = __offset(34); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int ccdataMasterListLength() { int o = __offset(34); return o != 0 ? __vector_len(o) : 0; }
  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntry.Vector ccdataMasterListVector() { return ccdataMasterListVector(new me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntry.Vector()); }
  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntry.Vector ccdataMasterListVector(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntry.Vector obj) { int o = __offset(34); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcData unk16(int j) { return unk16(new me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcData(), j); }
  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcData unk16(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcData obj, int j) { int o = __offset(36); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int unk16Length() { int o = __offset(36); return o != 0 ? __vector_len(o) : 0; }
  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcData.Vector unk16Vector() { return unk16Vector(new me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcData.Vector()); }
  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcData.Vector unk16Vector(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcData.Vector obj) { int o = __offset(36); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public boolean res17() { int o = __offset(38); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createtrinity_CharacterCreationMasterComponent(FlatBufferBuilder builder,
      int nameOffset,
      boolean res1,
      float unk2,
      float unk3,
      float unk4,
      boolean res5,
      float unk6,
      long unk7,
      float unk8,
      long unk9,
      float unk10,
      long unk11,
      float unk12,
      long res13,
      long res14,
      int ccdataMasterListOffset,
      int unk16Offset,
      boolean res17) {
    builder.startTable(18);
    trinity_CharacterCreationMasterComponent.addUnk16(builder, unk16Offset);
    trinity_CharacterCreationMasterComponent.addCcdataMasterList(builder, ccdataMasterListOffset);
    trinity_CharacterCreationMasterComponent.addRes14(builder, res14);
    trinity_CharacterCreationMasterComponent.addRes13(builder, res13);
    trinity_CharacterCreationMasterComponent.addUnk12(builder, unk12);
    trinity_CharacterCreationMasterComponent.addUnk11(builder, unk11);
    trinity_CharacterCreationMasterComponent.addUnk10(builder, unk10);
    trinity_CharacterCreationMasterComponent.addUnk9(builder, unk9);
    trinity_CharacterCreationMasterComponent.addUnk8(builder, unk8);
    trinity_CharacterCreationMasterComponent.addUnk7(builder, unk7);
    trinity_CharacterCreationMasterComponent.addUnk6(builder, unk6);
    trinity_CharacterCreationMasterComponent.addUnk4(builder, unk4);
    trinity_CharacterCreationMasterComponent.addUnk3(builder, unk3);
    trinity_CharacterCreationMasterComponent.addUnk2(builder, unk2);
    trinity_CharacterCreationMasterComponent.addName(builder, nameOffset);
    trinity_CharacterCreationMasterComponent.addRes17(builder, res17);
    trinity_CharacterCreationMasterComponent.addRes5(builder, res5);
    trinity_CharacterCreationMasterComponent.addRes1(builder, res1);
    return trinity_CharacterCreationMasterComponent.endtrinity_CharacterCreationMasterComponent(builder);
  }

  public static void starttrinity_CharacterCreationMasterComponent(FlatBufferBuilder builder) { builder.startTable(18); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addRes1(FlatBufferBuilder builder, boolean res1) { builder.addBoolean(1, res1, false); }
  public static void addUnk2(FlatBufferBuilder builder, float unk2) { builder.addFloat(2, unk2, 0.0f); }
  public static void addUnk3(FlatBufferBuilder builder, float unk3) { builder.addFloat(3, unk3, 0.0f); }
  public static void addUnk4(FlatBufferBuilder builder, float unk4) { builder.addFloat(4, unk4, 0.0f); }
  public static void addRes5(FlatBufferBuilder builder, boolean res5) { builder.addBoolean(5, res5, false); }
  public static void addUnk6(FlatBufferBuilder builder, float unk6) { builder.addFloat(6, unk6, 0.0f); }
  public static void addUnk7(FlatBufferBuilder builder, long unk7) { builder.addInt(7, (int) unk7, (int) 0L); }
  public static void addUnk8(FlatBufferBuilder builder, float unk8) { builder.addFloat(8, unk8, 0.0f); }
  public static void addUnk9(FlatBufferBuilder builder, long unk9) { builder.addInt(9, (int) unk9, (int) 0L); }
  public static void addUnk10(FlatBufferBuilder builder, float unk10) { builder.addFloat(10, unk10, 0.0f); }
  public static void addUnk11(FlatBufferBuilder builder, long unk11) { builder.addInt(11, (int) unk11, (int) 0L); }
  public static void addUnk12(FlatBufferBuilder builder, float unk12) { builder.addFloat(12, unk12, 0.0f); }
  public static void addRes13(FlatBufferBuilder builder, long res13) { builder.addInt(13, (int) res13, (int) 0L); }
  public static void addRes14(FlatBufferBuilder builder, long res14) { builder.addInt(14, (int) res14, (int) 0L); }
  public static void addCcdataMasterList(FlatBufferBuilder builder, int ccdataMasterListOffset) { builder.addOffset(15, ccdataMasterListOffset, 0); }
  public static int createCcdataMasterListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCcdataMasterListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addUnk16(FlatBufferBuilder builder, int unk16Offset) { builder.addOffset(16, unk16Offset, 0); }
  public static int createUnk16Vector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startUnk16Vector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRes17(FlatBufferBuilder builder, boolean res17) { builder.addBoolean(17, res17, false); }
  public static int endtrinity_CharacterCreationMasterComponent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishtrinity_CharacterCreationMasterComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedtrinity_CharacterCreationMasterComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public trinity_CharacterCreationMasterComponent get(int j) { return get(new trinity_CharacterCreationMasterComponent(), j); }
    public trinity_CharacterCreationMasterComponent get(trinity_CharacterCreationMasterComponent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public trinity_CharacterCreationMasterComponentT unpack() {
    trinity_CharacterCreationMasterComponentT _o = new trinity_CharacterCreationMasterComponentT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(trinity_CharacterCreationMasterComponentT _o) {
    String _oName = name();
    _o.setName(_oName);
    boolean _oRes1 = res1();
    _o.setRes1(_oRes1);
    float _oUnk2 = unk2();
    _o.setUnk2(_oUnk2);
    float _oUnk3 = unk3();
    _o.setUnk3(_oUnk3);
    float _oUnk4 = unk4();
    _o.setUnk4(_oUnk4);
    boolean _oRes5 = res5();
    _o.setRes5(_oRes5);
    float _oUnk6 = unk6();
    _o.setUnk6(_oUnk6);
    long _oUnk7 = unk7();
    _o.setUnk7(_oUnk7);
    float _oUnk8 = unk8();
    _o.setUnk8(_oUnk8);
    long _oUnk9 = unk9();
    _o.setUnk9(_oUnk9);
    float _oUnk10 = unk10();
    _o.setUnk10(_oUnk10);
    long _oUnk11 = unk11();
    _o.setUnk11(_oUnk11);
    float _oUnk12 = unk12();
    _o.setUnk12(_oUnk12);
    long _oRes13 = res13();
    _o.setRes13(_oRes13);
    long _oRes14 = res14();
    _o.setRes14(_oRes14);
    me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntryT[] _oCcdataMasterList = new me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntryT[ccdataMasterListLength()];
    for (int _j = 0; _j < ccdataMasterListLength(); ++_j) {_oCcdataMasterList[_j] = (ccdataMasterList(_j) != null ? ccdataMasterList(_j).unpack() : null);}
    _o.setCcdataMasterList(_oCcdataMasterList);
    me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcDataT[] _oUnk16 = new me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcDataT[unk16Length()];
    for (int _j = 0; _j < unk16Length(); ++_j) {_oUnk16[_j] = (unk16(_j) != null ? unk16(_j).unpack() : null);}
    _o.setUnk16(_oUnk16);
    boolean _oRes17 = res17();
    _o.setRes17(_oRes17);
  }
  public static int pack(FlatBufferBuilder builder, trinity_CharacterCreationMasterComponentT _o) {
    if (_o == null) return 0;
    int _name = _o.getName() == null ? 0 : builder.createString(_o.getName());
    int _ccdataMasterList = 0;
    if (_o.getCcdataMasterList() != null) {
      int[] __ccdataMasterList = new int[_o.getCcdataMasterList().length];
      int _j = 0;
      for (me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntryT _e : _o.getCcdataMasterList()) { __ccdataMasterList[_j] = me.hydos.trifecta.flatbuffers.Titan.TrinityScene.CcdataMasterEntry.pack(builder, _e); _j++;}
      _ccdataMasterList = createCcdataMasterListVector(builder, __ccdataMasterList);
    }
    int _unk16 = 0;
    if (_o.getUnk16() != null) {
      int[] __unk16 = new int[_o.getUnk16().length];
      int _j = 0;
      for (me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcDataT _e : _o.getUnk16()) { __unk16[_j] = me.hydos.trifecta.flatbuffers.Titan.TrinityScene.UnknownCcData.pack(builder, _e); _j++;}
      _unk16 = createUnk16Vector(builder, __unk16);
    }
    return createtrinity_CharacterCreationMasterComponent(
      builder,
      _name,
      _o.getRes1(),
      _o.getUnk2(),
      _o.getUnk3(),
      _o.getUnk4(),
      _o.getRes5(),
      _o.getUnk6(),
      _o.getUnk7(),
      _o.getUnk8(),
      _o.getUnk9(),
      _o.getUnk10(),
      _o.getUnk11(),
      _o.getUnk12(),
      _o.getRes13(),
      _o.getRes14(),
      _ccdataMasterList,
      _unk16,
      _o.getRes17());
  }
}

