// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class trinity_SceneObjectT {
  private String name;
  private me.hydos.trifecta.flatbuffers.SRTT srt;
  private boolean unk2;
  private boolean unk3;
  private String unk4;
  private boolean unk5;
  private long unk6;
  private me.hydos.trifecta.flatbuffers.Titan.TrinityScene.additional_SRT_DataT[] additionalSrtdata;
  private String[] unk8;
  private me.hydos.trifecta.flatbuffers.Titan.TrinityScene.unknown_sceneObject_dataT unk9;

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public me.hydos.trifecta.flatbuffers.SRTT getSrt() { return srt; }

  public void setSrt(me.hydos.trifecta.flatbuffers.SRTT srt) { this.srt = srt; }

  public boolean getUnk2() { return unk2; }

  public void setUnk2(boolean unk2) { this.unk2 = unk2; }

  public boolean getUnk3() { return unk3; }

  public void setUnk3(boolean unk3) { this.unk3 = unk3; }

  public String getUnk4() { return unk4; }

  public void setUnk4(String unk4) { this.unk4 = unk4; }

  public boolean getUnk5() { return unk5; }

  public void setUnk5(boolean unk5) { this.unk5 = unk5; }

  public long getUnk6() { return unk6; }

  public void setUnk6(long unk6) { this.unk6 = unk6; }

  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.additional_SRT_DataT[] getAdditionalSrtdata() { return additionalSrtdata; }

  public void setAdditionalSrtdata(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.additional_SRT_DataT[] additionalSrtdata) { this.additionalSrtdata = additionalSrtdata; }

  public String[] getUnk8() { return unk8; }

  public void setUnk8(String[] unk8) { this.unk8 = unk8; }

  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.unknown_sceneObject_dataT getUnk9() { return unk9; }

  public void setUnk9(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.unknown_sceneObject_dataT unk9) { this.unk9 = unk9; }


  public trinity_SceneObjectT() {
    this.name = null;
    this.srt = null;
    this.unk2 = false;
    this.unk3 = false;
    this.unk4 = null;
    this.unk5 = false;
    this.unk6 = 0L;
    this.additionalSrtdata = null;
    this.unk8 = null;
    this.unk9 = null;
  }
  public static trinity_SceneObjectT deserializeFromBinary(byte[] fbBuffer) {
    return trinity_SceneObject.getRootAstrinity_SceneObject(ByteBuffer.wrap(fbBuffer)).unpack();
  }
  public byte[] serializeToBinary() {
    FlatBufferBuilder fbb = new FlatBufferBuilder();
    trinity_SceneObject.finishtrinity_SceneObjectBuffer(fbb, trinity_SceneObject.pack(fbb, this));
    return fbb.sizedByteArray();
  }
}

