// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class trinity_CollisionEventTriggerComponent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static trinity_CollisionEventTriggerComponent getRootAstrinity_CollisionEventTriggerComponent(ByteBuffer _bb) { return getRootAstrinity_CollisionEventTriggerComponent(_bb, new trinity_CollisionEventTriggerComponent()); }
  public static trinity_CollisionEventTriggerComponent getRootAstrinity_CollisionEventTriggerComponent(ByteBuffer _bb, trinity_CollisionEventTriggerComponent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public trinity_CollisionEventTriggerComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String unk0() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk0AsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer unk0InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String unk1() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk1AsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer unk1InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public long unk2() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String unk3() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk3AsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer unk3InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String unk4() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer unk4AsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer unk4InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public long unk5() { int o = __offset(14); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createtrinity_CollisionEventTriggerComponent(FlatBufferBuilder builder,
      int unk0Offset,
      int unk1Offset,
      long unk2,
      int unk3Offset,
      int unk4Offset,
      long unk5) {
    builder.startTable(6);
    trinity_CollisionEventTriggerComponent.addUnk5(builder, unk5);
    trinity_CollisionEventTriggerComponent.addUnk4(builder, unk4Offset);
    trinity_CollisionEventTriggerComponent.addUnk3(builder, unk3Offset);
    trinity_CollisionEventTriggerComponent.addUnk2(builder, unk2);
    trinity_CollisionEventTriggerComponent.addUnk1(builder, unk1Offset);
    trinity_CollisionEventTriggerComponent.addUnk0(builder, unk0Offset);
    return trinity_CollisionEventTriggerComponent.endtrinity_CollisionEventTriggerComponent(builder);
  }

  public static void starttrinity_CollisionEventTriggerComponent(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addUnk0(FlatBufferBuilder builder, int unk0Offset) { builder.addOffset(0, unk0Offset, 0); }
  public static void addUnk1(FlatBufferBuilder builder, int unk1Offset) { builder.addOffset(1, unk1Offset, 0); }
  public static void addUnk2(FlatBufferBuilder builder, long unk2) { builder.addInt(2, (int) unk2, (int) 0L); }
  public static void addUnk3(FlatBufferBuilder builder, int unk3Offset) { builder.addOffset(3, unk3Offset, 0); }
  public static void addUnk4(FlatBufferBuilder builder, int unk4Offset) { builder.addOffset(4, unk4Offset, 0); }
  public static void addUnk5(FlatBufferBuilder builder, long unk5) { builder.addInt(5, (int) unk5, (int) 0L); }
  public static int endtrinity_CollisionEventTriggerComponent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishtrinity_CollisionEventTriggerComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedtrinity_CollisionEventTriggerComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public trinity_CollisionEventTriggerComponent get(int j) { return get(new trinity_CollisionEventTriggerComponent(), j); }
    public trinity_CollisionEventTriggerComponent get(trinity_CollisionEventTriggerComponent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public trinity_CollisionEventTriggerComponentT unpack() {
    trinity_CollisionEventTriggerComponentT _o = new trinity_CollisionEventTriggerComponentT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(trinity_CollisionEventTriggerComponentT _o) {
    String _oUnk0 = unk0();
    _o.setUnk0(_oUnk0);
    String _oUnk1 = unk1();
    _o.setUnk1(_oUnk1);
    long _oUnk2 = unk2();
    _o.setUnk2(_oUnk2);
    String _oUnk3 = unk3();
    _o.setUnk3(_oUnk3);
    String _oUnk4 = unk4();
    _o.setUnk4(_oUnk4);
    long _oUnk5 = unk5();
    _o.setUnk5(_oUnk5);
  }
  public static int pack(FlatBufferBuilder builder, trinity_CollisionEventTriggerComponentT _o) {
    if (_o == null) return 0;
    int _unk0 = _o.getUnk0() == null ? 0 : builder.createString(_o.getUnk0());
    int _unk1 = _o.getUnk1() == null ? 0 : builder.createString(_o.getUnk1());
    int _unk3 = _o.getUnk3() == null ? 0 : builder.createString(_o.getUnk3());
    int _unk4 = _o.getUnk4() == null ? 0 : builder.createString(_o.getUnk4());
    return createtrinity_CollisionEventTriggerComponent(
      builder,
      _unk0,
      _unk1,
      _o.getUnk2(),
      _unk3,
      _unk4,
      _o.getUnk5());
  }
}

