// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class trinity_CollisionComponentT {
  private int unk0;
  private me.hydos.trifecta.flatbuffers.Titan.TrinityScene.someTableT unk1;

  public int getUnk0() { return unk0; }

  public void setUnk0(int unk0) { this.unk0 = unk0; }

  public me.hydos.trifecta.flatbuffers.Titan.TrinityScene.someTableT getUnk1() { return unk1; }

  public void setUnk1(me.hydos.trifecta.flatbuffers.Titan.TrinityScene.someTableT unk1) { this.unk1 = unk1; }


  public trinity_CollisionComponentT() {
    this.unk0 = 0;
    this.unk1 = null;
  }
  public static trinity_CollisionComponentT deserializeFromBinary(byte[] fbBuffer) {
    return trinity_CollisionComponent.getRootAstrinity_CollisionComponent(ByteBuffer.wrap(fbBuffer)).unpack();
  }
  public byte[] serializeToBinary() {
    FlatBufferBuilder fbb = new FlatBufferBuilder();
    trinity_CollisionComponent.finishtrinity_CollisionComponentBuffer(fbb, trinity_CollisionComponent.pack(fbb, this));
    return fbb.sizedByteArray();
  }
}

