// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class trinity_NavigatorComponent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static trinity_NavigatorComponent getRootAstrinity_NavigatorComponent(ByteBuffer _bb) { return getRootAstrinity_NavigatorComponent(_bb, new trinity_NavigatorComponent()); }
  public static trinity_NavigatorComponent getRootAstrinity_NavigatorComponent(ByteBuffer _bb, trinity_NavigatorComponent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public trinity_NavigatorComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String componentName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer componentNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer componentNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public float unk1() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk2() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk3() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk4() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk5() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk6() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk7() { int o = __offset(18); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk8() { int o = __offset(20); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk9() { int o = __offset(22); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk10() { int o = __offset(24); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk11() { int o = __offset(26); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk12() { int o = __offset(28); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk13() { int o = __offset(30); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk14() { int o = __offset(32); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float unk15() { int o = __offset(34); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public long unk16() { int o = __offset(36); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createtrinity_NavigatorComponent(FlatBufferBuilder builder,
      int componentNameOffset,
      float unk1,
      float unk2,
      float unk3,
      float unk4,
      float unk5,
      float unk6,
      float unk7,
      float unk8,
      float unk9,
      float unk10,
      float unk11,
      float unk12,
      float unk13,
      float unk14,
      float unk15,
      long unk16) {
    builder.startTable(17);
    trinity_NavigatorComponent.addUnk16(builder, unk16);
    trinity_NavigatorComponent.addUnk15(builder, unk15);
    trinity_NavigatorComponent.addUnk14(builder, unk14);
    trinity_NavigatorComponent.addUnk13(builder, unk13);
    trinity_NavigatorComponent.addUnk12(builder, unk12);
    trinity_NavigatorComponent.addUnk11(builder, unk11);
    trinity_NavigatorComponent.addUnk10(builder, unk10);
    trinity_NavigatorComponent.addUnk9(builder, unk9);
    trinity_NavigatorComponent.addUnk8(builder, unk8);
    trinity_NavigatorComponent.addUnk7(builder, unk7);
    trinity_NavigatorComponent.addUnk6(builder, unk6);
    trinity_NavigatorComponent.addUnk5(builder, unk5);
    trinity_NavigatorComponent.addUnk4(builder, unk4);
    trinity_NavigatorComponent.addUnk3(builder, unk3);
    trinity_NavigatorComponent.addUnk2(builder, unk2);
    trinity_NavigatorComponent.addUnk1(builder, unk1);
    trinity_NavigatorComponent.addComponentName(builder, componentNameOffset);
    return trinity_NavigatorComponent.endtrinity_NavigatorComponent(builder);
  }

  public static void starttrinity_NavigatorComponent(FlatBufferBuilder builder) { builder.startTable(17); }
  public static void addComponentName(FlatBufferBuilder builder, int componentNameOffset) { builder.addOffset(0, componentNameOffset, 0); }
  public static void addUnk1(FlatBufferBuilder builder, float unk1) { builder.addFloat(1, unk1, 0.0f); }
  public static void addUnk2(FlatBufferBuilder builder, float unk2) { builder.addFloat(2, unk2, 0.0f); }
  public static void addUnk3(FlatBufferBuilder builder, float unk3) { builder.addFloat(3, unk3, 0.0f); }
  public static void addUnk4(FlatBufferBuilder builder, float unk4) { builder.addFloat(4, unk4, 0.0f); }
  public static void addUnk5(FlatBufferBuilder builder, float unk5) { builder.addFloat(5, unk5, 0.0f); }
  public static void addUnk6(FlatBufferBuilder builder, float unk6) { builder.addFloat(6, unk6, 0.0f); }
  public static void addUnk7(FlatBufferBuilder builder, float unk7) { builder.addFloat(7, unk7, 0.0f); }
  public static void addUnk8(FlatBufferBuilder builder, float unk8) { builder.addFloat(8, unk8, 0.0f); }
  public static void addUnk9(FlatBufferBuilder builder, float unk9) { builder.addFloat(9, unk9, 0.0f); }
  public static void addUnk10(FlatBufferBuilder builder, float unk10) { builder.addFloat(10, unk10, 0.0f); }
  public static void addUnk11(FlatBufferBuilder builder, float unk11) { builder.addFloat(11, unk11, 0.0f); }
  public static void addUnk12(FlatBufferBuilder builder, float unk12) { builder.addFloat(12, unk12, 0.0f); }
  public static void addUnk13(FlatBufferBuilder builder, float unk13) { builder.addFloat(13, unk13, 0.0f); }
  public static void addUnk14(FlatBufferBuilder builder, float unk14) { builder.addFloat(14, unk14, 0.0f); }
  public static void addUnk15(FlatBufferBuilder builder, float unk15) { builder.addFloat(15, unk15, 0.0f); }
  public static void addUnk16(FlatBufferBuilder builder, long unk16) { builder.addInt(16, (int) unk16, (int) 0L); }
  public static int endtrinity_NavigatorComponent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishtrinity_NavigatorComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedtrinity_NavigatorComponentBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public trinity_NavigatorComponent get(int j) { return get(new trinity_NavigatorComponent(), j); }
    public trinity_NavigatorComponent get(trinity_NavigatorComponent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public trinity_NavigatorComponentT unpack() {
    trinity_NavigatorComponentT _o = new trinity_NavigatorComponentT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(trinity_NavigatorComponentT _o) {
    String _oComponentName = componentName();
    _o.setComponentName(_oComponentName);
    float _oUnk1 = unk1();
    _o.setUnk1(_oUnk1);
    float _oUnk2 = unk2();
    _o.setUnk2(_oUnk2);
    float _oUnk3 = unk3();
    _o.setUnk3(_oUnk3);
    float _oUnk4 = unk4();
    _o.setUnk4(_oUnk4);
    float _oUnk5 = unk5();
    _o.setUnk5(_oUnk5);
    float _oUnk6 = unk6();
    _o.setUnk6(_oUnk6);
    float _oUnk7 = unk7();
    _o.setUnk7(_oUnk7);
    float _oUnk8 = unk8();
    _o.setUnk8(_oUnk8);
    float _oUnk9 = unk9();
    _o.setUnk9(_oUnk9);
    float _oUnk10 = unk10();
    _o.setUnk10(_oUnk10);
    float _oUnk11 = unk11();
    _o.setUnk11(_oUnk11);
    float _oUnk12 = unk12();
    _o.setUnk12(_oUnk12);
    float _oUnk13 = unk13();
    _o.setUnk13(_oUnk13);
    float _oUnk14 = unk14();
    _o.setUnk14(_oUnk14);
    float _oUnk15 = unk15();
    _o.setUnk15(_oUnk15);
    long _oUnk16 = unk16();
    _o.setUnk16(_oUnk16);
  }
  public static int pack(FlatBufferBuilder builder, trinity_NavigatorComponentT _o) {
    if (_o == null) return 0;
    int _componentName = _o.getComponentName() == null ? 0 : builder.createString(_o.getComponentName());
    return createtrinity_NavigatorComponent(
      builder,
      _componentName,
      _o.getUnk1(),
      _o.getUnk2(),
      _o.getUnk3(),
      _o.getUnk4(),
      _o.getUnk5(),
      _o.getUnk6(),
      _o.getUnk7(),
      _o.getUnk8(),
      _o.getUnk9(),
      _o.getUnk10(),
      _o.getUnk11(),
      _o.getUnk12(),
      _o.getUnk13(),
      _o.getUnk14(),
      _o.getUnk15(),
      _o.getUnk16());
  }
}

