// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.TrinityScene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class unknown_sceneObject_dataT {
  private me.hydos.trifecta.flatbuffers.Vec3fT unk1;
  private float unk2;

  public me.hydos.trifecta.flatbuffers.Vec3fT getUnk1() { return unk1; }

  public void setUnk1(me.hydos.trifecta.flatbuffers.Vec3fT unk1) { this.unk1 = unk1; }

  public float getUnk2() { return unk2; }

  public void setUnk2(float unk2) { this.unk2 = unk2; }


  public unknown_sceneObject_dataT() {
    this.unk1 = new me.hydos.trifecta.flatbuffers.Vec3fT();
    this.unk2 = 0.0f;
  }
}

