// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class BoneMatrixT {
  private me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T x;
  private me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T y;
  private me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T z;
  private me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T w;

  public me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T getX() { return x; }

  public void setX(me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T x) { this.x = x; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T getY() { return y; }

  public void setY(me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T y) { this.y = y; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T getZ() { return z; }

  public void setZ(me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T z) { this.z = z; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T getW() { return w; }

  public void setW(me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T w) { this.w = w; }


  public BoneMatrixT() {
    this.x = new me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T();
    this.y = new me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T();
    this.z = new me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T();
    this.w = new me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T();
  }
}

