// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class BoneT {
  private int inheritPosition;
  private int unkBool2;
  private me.hydos.trifecta.flatbuffers.Titan.Model.BoneMatrixT matrix;

  public int getInheritPosition() { return inheritPosition; }

  public void setInheritPosition(int inheritPosition) { this.inheritPosition = inheritPosition; }

  public int getUnkBool2() { return unkBool2; }

  public void setUnkBool2(int unkBool2) { this.unkBool2 = unkBool2; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.BoneMatrixT getMatrix() { return matrix; }

  public void setMatrix(me.hydos.trifecta.flatbuffers.Titan.Model.BoneMatrixT matrix) { this.matrix = matrix; }


  public BoneT() {
    this.inheritPosition = 0;
    this.unkBool2 = 0;
    this.matrix = null;
  }
}

