// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class FloatParameterT {
  private String floatName;
  private float floatValue;

  public String getFloatName() { return floatName; }

  public void setFloatName(String floatName) { this.floatName = floatName; }

  public float getFloatValue() { return floatValue; }

  public void setFloatValue(float floatValue) { this.floatValue = floatValue; }


  public FloatParameterT() {
    this.floatName = null;
    this.floatValue = 0.0f;
  }
}

