// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class IKControlT {
  private String ikName;
  private String ikChainStart;
  private String ikChainEnd;
  private String ikType;
  private long res4;
  private me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T ikPos;
  private me.hydos.trifecta.flatbuffers.Titan.Model.Vec4T ikRot;

  public String getIkName() { return ikName; }

  public void setIkName(String ikName) { this.ikName = ikName; }

  public String getIkChainStart() { return ikChainStart; }

  public void setIkChainStart(String ikChainStart) { this.ikChainStart = ikChainStart; }

  public String getIkChainEnd() { return ikChainEnd; }

  public void setIkChainEnd(String ikChainEnd) { this.ikChainEnd = ikChainEnd; }

  public String getIkType() { return ikType; }

  public void setIkType(String ikType) { this.ikType = ikType; }

  public long getRes4() { return res4; }

  public void setRes4(long res4) { this.res4 = res4; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T getIkPos() { return ikPos; }

  public void setIkPos(me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T ikPos) { this.ikPos = ikPos; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.Vec4T getIkRot() { return ikRot; }

  public void setIkRot(me.hydos.trifecta.flatbuffers.Titan.Model.Vec4T ikRot) { this.ikRot = ikRot; }


  public IKControlT() {
    this.ikName = null;
    this.ikChainStart = null;
    this.ikChainEnd = null;
    this.ikType = null;
    this.res4 = 0L;
    this.ikPos = new me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T();
    this.ikRot = new me.hydos.trifecta.flatbuffers.Titan.Model.Vec4T();
  }
}

