// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class LodT {
  private me.hydos.trifecta.flatbuffers.Titan.Model.LodIndexT[] index;
  private String lodType;

  public me.hydos.trifecta.flatbuffers.Titan.Model.LodIndexT[] getIndex() { return index; }

  public void setIndex(me.hydos.trifecta.flatbuffers.Titan.Model.LodIndexT[] index) { this.index = index; }

  public String getLodType() { return lodType; }

  public void setLodType(String lodType) { this.lodType = lodType; }


  public LodT() {
    this.index = null;
    this.lodType = null;
  }
}

