// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class LookupTableT {
  private String shapeName;
  private String name;
  private me.hydos.trifecta.flatbuffers.Titan.Model.Vec3iT unk2;
  private String[] meshNames;
  private me.hydos.trifecta.flatbuffers.Titan.Model.Table2T[] baseShape;
  private me.hydos.trifecta.flatbuffers.Titan.Model.Vec3fT[] somePositions;

  public String getShapeName() { return shapeName; }

  public void setShapeName(String shapeName) { this.shapeName = shapeName; }

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.Vec3iT getUnk2() { return unk2; }

  public void setUnk2(me.hydos.trifecta.flatbuffers.Titan.Model.Vec3iT unk2) { this.unk2 = unk2; }

  public String[] getMeshNames() { return meshNames; }

  public void setMeshNames(String[] meshNames) { this.meshNames = meshNames; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.Table2T[] getBaseShape() { return baseShape; }

  public void setBaseShape(me.hydos.trifecta.flatbuffers.Titan.Model.Table2T[] baseShape) { this.baseShape = baseShape; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.Vec3fT[] getSomePositions() { return somePositions; }

  public void setSomePositions(me.hydos.trifecta.flatbuffers.Titan.Model.Vec3fT[] somePositions) { this.somePositions = somePositions; }


  public LookupTableT() {
    this.shapeName = null;
    this.name = null;
    this.unk2 = new me.hydos.trifecta.flatbuffers.Titan.Model.Vec3iT();
    this.meshNames = null;
    this.baseShape = null;
    this.somePositions = null;
  }
}

