// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class MaterialInfoT {
  private long polyCount;
  private long polyOffset;
  private long shUnk3;
  private String materialName;
  private int shUnk4;

  public long getPolyCount() { return polyCount; }

  public void setPolyCount(long polyCount) { this.polyCount = polyCount; }

  public long getPolyOffset() { return polyOffset; }

  public void setPolyOffset(long polyOffset) { this.polyOffset = polyOffset; }

  public long getShUnk3() { return shUnk3; }

  public void setShUnk3(long shUnk3) { this.shUnk3 = shUnk3; }

  public String getMaterialName() { return materialName; }

  public void setMaterialName(String materialName) { this.materialName = materialName; }

  public int getShUnk4() { return shUnk4; }

  public void setShUnk4(int shUnk4) { this.shUnk4 = shUnk4; }


  public MaterialInfoT() {
    this.polyCount = 0L;
    this.polyOffset = 0L;
    this.shUnk3 = 0L;
    this.materialName = null;
    this.shUnk4 = -1;
  }
}

