// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class MeshShapeT {
  private String meshShapeName;
  private me.hydos.trifecta.flatbuffers.Titan.Model.BoundingBoxT bounds;
  private long polygonType;
  private me.hydos.trifecta.flatbuffers.Titan.Model.VertexAccessorsT[] attributes;
  private me.hydos.trifecta.flatbuffers.Titan.Model.MaterialInfoT[] materials;
  private long res0;
  private long res1;
  private long res2;
  private long res3;
  private me.hydos.trifecta.flatbuffers.Titan.Model.SphereT clipSphere;
  private me.hydos.trifecta.flatbuffers.Titan.Model.InfluenceT[] influence;
  private me.hydos.trifecta.flatbuffers.Titan.Model.VisShapeT[] visShapes;
  private String meshName;
  private long unk13;
  private me.hydos.trifecta.flatbuffers.Titan.Model.MorphShapeT[] morphShape;

  public String getMeshShapeName() { return meshShapeName; }

  public void setMeshShapeName(String meshShapeName) { this.meshShapeName = meshShapeName; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.BoundingBoxT getBounds() { return bounds; }

  public void setBounds(me.hydos.trifecta.flatbuffers.Titan.Model.BoundingBoxT bounds) { this.bounds = bounds; }

  public long getPolygonType() { return polygonType; }

  public void setPolygonType(long polygonType) { this.polygonType = polygonType; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.VertexAccessorsT[] getAttributes() { return attributes; }

  public void setAttributes(me.hydos.trifecta.flatbuffers.Titan.Model.VertexAccessorsT[] attributes) { this.attributes = attributes; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.MaterialInfoT[] getMaterials() { return materials; }

  public void setMaterials(me.hydos.trifecta.flatbuffers.Titan.Model.MaterialInfoT[] materials) { this.materials = materials; }

  public long getRes0() { return res0; }

  public void setRes0(long res0) { this.res0 = res0; }

  public long getRes1() { return res1; }

  public void setRes1(long res1) { this.res1 = res1; }

  public long getRes2() { return res2; }

  public void setRes2(long res2) { this.res2 = res2; }

  public long getRes3() { return res3; }

  public void setRes3(long res3) { this.res3 = res3; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.SphereT getClipSphere() { return clipSphere; }

  public void setClipSphere(me.hydos.trifecta.flatbuffers.Titan.Model.SphereT clipSphere) { this.clipSphere = clipSphere; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.InfluenceT[] getInfluence() { return influence; }

  public void setInfluence(me.hydos.trifecta.flatbuffers.Titan.Model.InfluenceT[] influence) { this.influence = influence; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.VisShapeT[] getVisShapes() { return visShapes; }

  public void setVisShapes(me.hydos.trifecta.flatbuffers.Titan.Model.VisShapeT[] visShapes) { this.visShapes = visShapes; }

  public String getMeshName() { return meshName; }

  public void setMeshName(String meshName) { this.meshName = meshName; }

  public long getUnk13() { return unk13; }

  public void setUnk13(long unk13) { this.unk13 = unk13; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.MorphShapeT[] getMorphShape() { return morphShape; }

  public void setMorphShape(me.hydos.trifecta.flatbuffers.Titan.Model.MorphShapeT[] morphShape) { this.morphShape = morphShape; }


  public MeshShapeT() {
    this.meshShapeName = null;
    this.bounds = null;
    this.polygonType = 0L;
    this.attributes = null;
    this.materials = null;
    this.res0 = 0L;
    this.res1 = 0L;
    this.res2 = 0L;
    this.res3 = 0L;
    this.clipSphere = new me.hydos.trifecta.flatbuffers.Titan.Model.SphereT();
    this.influence = null;
    this.visShapes = null;
    this.meshName = null;
    this.unk13 = 0L;
    this.morphShape = null;
  }
}

