// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class RGBAT {
  private float r;
  private float g;
  private float b;
  private float a;

  public float getR() { return r; }

  public void setR(float r) { this.r = r; }

  public float getG() { return g; }

  public void setG(float g) { this.g = g; }

  public float getB() { return b; }

  public void setB(float b) { this.b = b; }

  public float getA() { return a; }

  public void setA(float a) { this.a = a; }


  public RGBAT() {
    this.r = 0.0f;
    this.g = 0.0f;
    this.b = 0.0f;
    this.a = 0.0f;
  }
}

