// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class SamplerStateT {
  private long samplerState0;
  private long samplerState1;
  private long samplerState2;
  private long samplerState3;
  private long samplerState4;
  private long samplerState5;
  private long samplerState6;
  private long samplerState7;
  private long samplerState8;
  private long repeatU;
  private long repeatV;
  private long repeatW;
  private me.hydos.trifecta.flatbuffers.Titan.Model.RGBAT borderColor;

  public long getSamplerState0() { return samplerState0; }

  public void setSamplerState0(long samplerState0) { this.samplerState0 = samplerState0; }

  public long getSamplerState1() { return samplerState1; }

  public void setSamplerState1(long samplerState1) { this.samplerState1 = samplerState1; }

  public long getSamplerState2() { return samplerState2; }

  public void setSamplerState2(long samplerState2) { this.samplerState2 = samplerState2; }

  public long getSamplerState3() { return samplerState3; }

  public void setSamplerState3(long samplerState3) { this.samplerState3 = samplerState3; }

  public long getSamplerState4() { return samplerState4; }

  public void setSamplerState4(long samplerState4) { this.samplerState4 = samplerState4; }

  public long getSamplerState5() { return samplerState5; }

  public void setSamplerState5(long samplerState5) { this.samplerState5 = samplerState5; }

  public long getSamplerState6() { return samplerState6; }

  public void setSamplerState6(long samplerState6) { this.samplerState6 = samplerState6; }

  public long getSamplerState7() { return samplerState7; }

  public void setSamplerState7(long samplerState7) { this.samplerState7 = samplerState7; }

  public long getSamplerState8() { return samplerState8; }

  public void setSamplerState8(long samplerState8) { this.samplerState8 = samplerState8; }

  public long getRepeatU() { return repeatU; }

  public void setRepeatU(long repeatU) { this.repeatU = repeatU; }

  public long getRepeatV() { return repeatV; }

  public void setRepeatV(long repeatV) { this.repeatV = repeatV; }

  public long getRepeatW() { return repeatW; }

  public void setRepeatW(long repeatW) { this.repeatW = repeatW; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.RGBAT getBorderColor() { return borderColor; }

  public void setBorderColor(me.hydos.trifecta.flatbuffers.Titan.Model.RGBAT borderColor) { this.borderColor = borderColor; }


  public SamplerStateT() {
    this.samplerState0 = 0L;
    this.samplerState1 = 0L;
    this.samplerState2 = 0L;
    this.samplerState3 = 0L;
    this.samplerState4 = 0L;
    this.samplerState5 = 0L;
    this.samplerState6 = 0L;
    this.samplerState7 = 0L;
    this.samplerState8 = 0L;
    this.repeatU = 0L;
    this.repeatV = 0L;
    this.repeatW = 0L;
    this.borderColor = new me.hydos.trifecta.flatbuffers.Titan.Model.RGBAT();
  }
}

