// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class ShaderT {
  private String shaderName;
  private me.hydos.trifecta.flatbuffers.Titan.Model.StringParameterT[] shaderValues;

  public String getShaderName() { return shaderName; }

  public void setShaderName(String shaderName) { this.shaderName = shaderName; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.StringParameterT[] getShaderValues() { return shaderValues; }

  public void setShaderValues(me.hydos.trifecta.flatbuffers.Titan.Model.StringParameterT[] shaderValues) { this.shaderValues = shaderValues; }


  public ShaderT() {
    this.shaderName = null;
    this.shaderValues = null;
  }
}

