// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class StringParameterT {
  private String stringName;
  private String stringValue;

  public String getStringName() { return stringName; }

  public void setStringName(String stringName) { this.stringName = stringName; }

  public String getStringValue() { return stringValue; }

  public void setStringValue(String stringValue) { this.stringValue = stringValue; }


  public StringParameterT() {
    this.stringName = null;
    this.stringValue = null;
  }
}

