// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class TransformNodeT {
  private String name;
  private me.hydos.trifecta.flatbuffers.Titan.Model.TransformT transform;
  private me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T scalePivot;
  private me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T rotatePivot;
  private int parentIdx;
  private int rigIdx;
  private String effectNode;
  private long type;

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.TransformT getTransform() { return transform; }

  public void setTransform(me.hydos.trifecta.flatbuffers.Titan.Model.TransformT transform) { this.transform = transform; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T getScalePivot() { return scalePivot; }

  public void setScalePivot(me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T scalePivot) { this.scalePivot = scalePivot; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T getRotatePivot() { return rotatePivot; }

  public void setRotatePivot(me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T rotatePivot) { this.rotatePivot = rotatePivot; }

  public int getParentIdx() { return parentIdx; }

  public void setParentIdx(int parentIdx) { this.parentIdx = parentIdx; }

  public int getRigIdx() { return rigIdx; }

  public void setRigIdx(int rigIdx) { this.rigIdx = rigIdx; }

  public String getEffectNode() { return effectNode; }

  public void setEffectNode(String effectNode) { this.effectNode = effectNode; }

  public long getType() { return type; }

  public void setType(long type) { this.type = type; }


  public TransformNodeT() {
    this.name = null;
    this.transform = null;
    this.scalePivot = new me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T();
    this.rotatePivot = new me.hydos.trifecta.flatbuffers.Titan.Model.Vec3T();
    this.parentIdx = -1;
    this.rigIdx = -1;
    this.effectNode = null;
    this.type = 0L;
  }
}

