// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class TRLTT extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static TRLTT getRootAsTRLTT(ByteBuffer _bb) { return getRootAsTRLTT(_bb, new TRLTT()); }
  public static TRLTT getRootAsTRLTT(ByteBuffer _bb, TRLTT obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TRLTT __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long res0() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public me.hydos.trifecta.flatbuffers.Titan.Model.LookupTable entries(int j) { return entries(new me.hydos.trifecta.flatbuffers.Titan.Model.LookupTable(), j); }
  public me.hydos.trifecta.flatbuffers.Titan.Model.LookupTable entries(me.hydos.trifecta.flatbuffers.Titan.Model.LookupTable obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int entriesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public me.hydos.trifecta.flatbuffers.Titan.Model.LookupTable.Vector entriesVector() { return entriesVector(new me.hydos.trifecta.flatbuffers.Titan.Model.LookupTable.Vector()); }
  public me.hydos.trifecta.flatbuffers.Titan.Model.LookupTable.Vector entriesVector(me.hydos.trifecta.flatbuffers.Titan.Model.LookupTable.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createTRLTT(FlatBufferBuilder builder,
      long res0,
      int entriesOffset) {
    builder.startTable(2);
    TRLTT.addEntries(builder, entriesOffset);
    TRLTT.addRes0(builder, res0);
    return TRLTT.endTRLTT(builder);
  }

  public static void startTRLTT(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addRes0(FlatBufferBuilder builder, long res0) { builder.addInt(0, (int) res0, (int) 0L); }
  public static void addEntries(FlatBufferBuilder builder, int entriesOffset) { builder.addOffset(1, entriesOffset, 0); }
  public static int createEntriesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEntriesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endTRLTT(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishTRLTTBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedTRLTTBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TRLTT get(int j) { return get(new TRLTT(), j); }
    public TRLTT get(TRLTT obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public TRLTTT unpack() {
    TRLTTT _o = new TRLTTT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(TRLTTT _o) {
    long _oRes0 = res0();
    _o.setRes0(_oRes0);
    me.hydos.trifecta.flatbuffers.Titan.Model.LookupTableT[] _oEntries = new me.hydos.trifecta.flatbuffers.Titan.Model.LookupTableT[entriesLength()];
    for (int _j = 0; _j < entriesLength(); ++_j) {_oEntries[_j] = (entries(_j) != null ? entries(_j).unpack() : null);}
    _o.setEntries(_oEntries);
  }
  public static int pack(FlatBufferBuilder builder, TRLTTT _o) {
    if (_o == null) return 0;
    int _entries = 0;
    if (_o.getEntries() != null) {
      int[] __entries = new int[_o.getEntries().length];
      int _j = 0;
      for (me.hydos.trifecta.flatbuffers.Titan.Model.LookupTableT _e : _o.getEntries()) { __entries[_j] = me.hydos.trifecta.flatbuffers.Titan.Model.LookupTable.pack(builder, _e); _j++;}
      _entries = createEntriesVector(builder, __entries);
    }
    return createTRLTT(
      builder,
      _o.getRes0(),
      _entries);
  }
}

