// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class VertexAccessorT {
  private int attr0;
  private long attribute;
  private long attributeLayer;
  private long type;
  private long position;

  public int getAttr0() { return attr0; }

  public void setAttr0(int attr0) { this.attr0 = attr0; }

  public long getAttribute() { return attribute; }

  public void setAttribute(long attribute) { this.attribute = attribute; }

  public long getAttributeLayer() { return attributeLayer; }

  public void setAttributeLayer(long attributeLayer) { this.attributeLayer = attributeLayer; }

  public long getType() { return type; }

  public void setType(long type) { this.type = type; }

  public long getPosition() { return position; }

  public void setPosition(long position) { this.position = position; }


  public VertexAccessorT() {
    this.attr0 = -1;
    this.attribute = 0L;
    this.attributeLayer = 0L;
    this.type = 0L;
    this.position = 0L;
  }
}

