// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class VertexAccessorsT {
  private me.hydos.trifecta.flatbuffers.Titan.Model.VertexAccessorT[] attrs;
  private me.hydos.trifecta.flatbuffers.Titan.Model.VertexSizeT[] size;

  public me.hydos.trifecta.flatbuffers.Titan.Model.VertexAccessorT[] getAttrs() { return attrs; }

  public void setAttrs(me.hydos.trifecta.flatbuffers.Titan.Model.VertexAccessorT[] attrs) { this.attrs = attrs; }

  public me.hydos.trifecta.flatbuffers.Titan.Model.VertexSizeT[] getSize() { return size; }

  public void setSize(me.hydos.trifecta.flatbuffers.Titan.Model.VertexSizeT[] size) { this.size = size; }


  public VertexAccessorsT() {
    this.attrs = null;
    this.size = null;
  }
}

