// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class SRTT {
  private me.hydos.trifecta.flatbuffers.Vec3fT scale;
  private me.hydos.trifecta.flatbuffers.Vec3fT rotation;
  private me.hydos.trifecta.flatbuffers.Vec3fT translation;

  public me.hydos.trifecta.flatbuffers.Vec3fT getScale() { return scale; }

  public void setScale(me.hydos.trifecta.flatbuffers.Vec3fT scale) { this.scale = scale; }

  public me.hydos.trifecta.flatbuffers.Vec3fT getRotation() { return rotation; }

  public void setRotation(me.hydos.trifecta.flatbuffers.Vec3fT rotation) { this.rotation = rotation; }

  public me.hydos.trifecta.flatbuffers.Vec3fT getTranslation() { return translation; }

  public void setTranslation(me.hydos.trifecta.flatbuffers.Vec3fT translation) { this.translation = translation; }


  public SRTT() {
    this.scale = new me.hydos.trifecta.flatbuffers.Vec3fT();
    this.rotation = new me.hydos.trifecta.flatbuffers.Vec3fT();
    this.translation = new me.hydos.trifecta.flatbuffers.Vec3fT();
  }
}

