// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Shader;

public class SlotMapT {
  private String slotName;
  private SlotMappingT[] slotValues;
  private int bool1;
  private int bool2;
  private int bool3;
  private int slotIndex;
  private long offset;

  public String getSlotName() { return slotName; }

  public void setSlotName(String slotName) { this.slotName = slotName; }

  public SlotMappingT[] getSlotValues() { return slotValues; }

  public void setSlotValues(SlotMappingT[] slotValues) { this.slotValues = slotValues; }

  public int getBool1() { return bool1; }

  public void setBool1(int bool1) { this.bool1 = bool1; }

  public int getBool2() { return bool2; }

  public void setBool2(int bool2) { this.bool2 = bool2; }

  public int getBool3() { return bool3; }

  public void setBool3(int bool3) { this.bool3 = bool3; }

  public int getSlotIndex() { return slotIndex; }

  public void setSlotIndex(int slotIndex) { this.slotIndex = slotIndex; }

  public long getOffset() { return offset; }

  public void setOffset(long offset) { this.offset = offset; }


  public SlotMapT() {
    this.slotName = null;
    this.slotValues = null;
    this.bool1 = 0;
    this.bool2 = 0;
    this.bool3 = 0;
    this.slotIndex = 0;
    this.offset = 0L;
  }
}

