// automatically generated by the FlatBuffers compiler, do not modify

package me.hydos.trifecta.flatbuffers.Titan.Shader;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SlotMapping extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static SlotMapping getRootAsSlotMapping(ByteBuffer _bb) { return getRootAsSlotMapping(_bb, new SlotMapping()); }
  public static SlotMapping getRootAsSlotMapping(ByteBuffer _bb, SlotMapping obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SlotMapping __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String stringValue() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer stringValueAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer stringValueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public long uintValue() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createSlotMapping(FlatBufferBuilder builder,
      int stringValueOffset,
      long uintValue) {
    builder.startTable(2);
    SlotMapping.addUintValue(builder, uintValue);
    SlotMapping.addStringValue(builder, stringValueOffset);
    return SlotMapping.endSlotMapping(builder);
  }

  public static void startSlotMapping(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addStringValue(FlatBufferBuilder builder, int stringValueOffset) { builder.addOffset(0, stringValueOffset, 0); }
  public static void addUintValue(FlatBufferBuilder builder, long uintValue) { builder.addInt(1, (int) uintValue, (int) 0L); }
  public static int endSlotMapping(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SlotMapping get(int j) { return get(new SlotMapping(), j); }
    public SlotMapping get(SlotMapping obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public SlotMappingT unpack() {
    SlotMappingT _o = new SlotMappingT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(SlotMappingT _o) {
    String _oStringValue = stringValue();
    _o.setStringValue(_oStringValue);
    long _oUintValue = uintValue();
    _o.setUintValue(_oUintValue);
  }
  public static int pack(FlatBufferBuilder builder, SlotMappingT _o) {
    if (_o == null) return 0;
    int _stringValue = _o.getStringValue() == null ? 0 : builder.createString(_o.getStringValue());
    return createSlotMapping(
      builder,
      _stringValue,
      _o.getUintValue());
  }
}

